### ISSUE TITLE
System.OutOfMemoryException during SetPartcloneContentMapping

### ISSUE THREAD

**Issue by JackOfBadTrades** [fiddyschmitt/clonezilla-util#28]
Hello!
It seems there's a bug somewhere in the app, because I'm getting that error when trying to open an image.
I've restored the image to a spare disk using Clonezilla, so it seems to be restorable. Also, it's an image of a partition rather than a whole disk, if that matters.
Command used:
`clonezilla-util.exe mount --input C:\ClonezillaTest\2019-01-03-08-img-OLDMOBOFUCKINGRIP --mount L:\`

PC specs, if needed:
Win10 x64 Enterprise LTSC 21H2 build 19044.2364
Processor AMD Ryzen 3 3100
RAM 16GB

Attaching log and screenshot of the Clonezilla folder. Edit: also attaching clonezilla-img file.
[clonezilla-img.txt](https://github.com/fiddyschmitt/clonezilla-util/files/10294160/clonezilla-img.txt)
[clonezilla-util-20221223.log](https://github.com/fiddyschmitt/clonezilla-util/files/10293960/clonezilla-util-20221223.log)
![explorer_kdqDs4Yw7P](https://user-images.githubusercontent.com/80150464/209310656-bba22811-a63d-4744-8f03-a792decd620a.png)

**Comment by fiddyschmitt** [comment]
Thanks Jack! I'll look into it in the next couple of days. And thanks for the detailed description and logs!!

**Comment by fiddyschmitt** [comment]
Hi Jack,

I'm trying to work out which version of Clonezilla was used. Could you please also post the contents of `Info-packages.txt` is it's available?

Thanks!
Fidel

**Comment by JackOfBadTrades** [comment]
I'm attaching it but... it's empty.
[Info-packages.txt](https://github.com/fiddyschmitt/clonezilla-util/files/10323641/Info-packages.txt)

Actually, I checked the same file in all my other backups and they're empty too.
I used the version that came with PartedMagic (PMAGIC_2019_01_03 to be exact), which is what I usually use to make backups. 

If my little knowledge of Clonezilla is right, you need the versions of these packages, right? (from the livecd):
```
clonezilla-3.30.35-noarch-2_pmagic
drbl-2.26.23-noarch-1_pmagic 
partclone-0.3.11-i386-drbl2_pmagic
```
Here's the full package list included in the livecd, if you need it:
[packages.txt](https://github.com/fiddyschmitt/clonezilla-util/files/10323694/packages.txt)

**Comment by fiddyschmitt** [comment]
Perfect! Thanks Jack - that's exactly what I needed

**Comment by fiddyschmitt** [comment]
Hi Jack,

What happens if you extract, using the following command?

`clonezilla-util.exe extract-partition-image --input "C:\ClonezillaTest\2019-01-03-08-img-OLDMOBOFUCKINGRIP" --output "C:\some_folder"
`

Hilarious backup name by the way hahaha

Fidel

**Comment by JackOfBadTrades** [comment]
Hmm, same error.
[clonezilla-util-20230101.log](https://github.com/fiddyschmitt/clonezilla-util/files/10328682/clonezilla-util-20230101.log)

Happy New Year by the way.

**Comment by fiddyschmitt** [comment]
Thanks for responding so quickly! Happy New Year!

I've just released [v2.0.4](https://github.com/fiddyschmitt/clonezilla-util/releases/tag/v2.0.4), which hopefully fixes the issue.

Could you please try it out when able?

Thanks,
Fidel

**Comment by JackOfBadTrades** [comment]
Well, it's not hanging on System.OutOfMemoryException anymore, but the bug still isn't fixed.
I ran the command from my first post and it managed to mount a drive. Thing is, it was HUGE:
![explorer_bToOdrcokB](https://user-images.githubusercontent.com/80150464/210191592-b2dd3dd2-6c7a-4a1a-9011-b720e462f51b.png)
A 1.17 TERABYTE volume! Of which only 120gb was in use.
Also, when I opened the drive it was completely empty. No files, no folders, no nothing.
I'm not sure what the app was doing, but it scared me so I stopped it. Log:
[clonezilla-util-20230101 - first.log](https://github.com/fiddyschmitt/clonezilla-util/files/10329881/clonezilla-util-20230101.-.first.log)

I ran it again but with the command you gave me. Log:
[clonezilla-util-20230101 - second.log](https://github.com/fiddyschmitt/clonezilla-util/files/10329899/clonezilla-util-20230101.-.second.log)
The app began to extract the image, however it was progressing excruciatingly slow, so I stopped it.

I can run it again, but it's gonna take a whole day to finish.

**Comment by fiddyschmitt** [comment]
Thanks Jack,

Don't worry about the drive size. It's artificial - I made it 10 times the space used, as you can see [here](https://github.com/fiddyschmitt/clonezilla-util/blob/61e6abedf19555e5d3a44902722c58b74d75ede5/libDokan/VFS/DokanVFS.cs#L497).

It looks like the `mount` command was working. It was in the middle of retrieving the list of files, and during that time the drive will be empty.

Please re-run the `mount` command again, and wait until you see this output
`[21:23:15 INF] Mounting complete. Mounted to: L:\`

**Comment by JackOfBadTrades** [comment]
Well, that sure took a while.  The "Retrieving a list of files." step took nearly a day to finish. Log:
[clonezilla-util-20230102.log](https://github.com/fiddyschmitt/clonezilla-util/files/10334452/clonezilla-util-20230102.log)

However, the bug IS fixed, even if another appeared.

Oh, quick note about the few file errors: it's mostly my fault. The name of these contain a Fullwidth solidus `／` (U+FF0F) which I imagine 7zip doesn't like and changed to a slash.
