### ISSUE TITLE
Can't open LUKS encrypted partition

### ISSUE THREAD

**Issue by ghost** [fiddyschmitt/clonezilla-util#8]
Hey I'm trying to extract a clonezilla image but I get error messages all the time.
```

PS C:\Users\dbj\Downloads\clonezilla-util.v1.6.0.win-x64> .\clonezilla-util.exe extract-partition-image --input D:\2022-08-12-17-manjaro\ocs_luks_Oeh.ext4-ptcl-img.gz --output D:\IMG
[20:13:20 INF] clonezilla-util v1.6.0
[20:13:20 INF] Waiting for Z:\ to be available.
[20:13:30 INF] ocs_luks_Oeh.ext4-ptcl-img uses Gzip compression, which is not seekable. Extracting first.
[20:13:30 INF] Using cached file: C:\Users\dbj\Downloads\clonezilla-util.v1.6.0.win-x64\cache\aabcb97129e4c3c49a7b4968047ab71a\cache.train
Unhandled exception. System.Exception: C:\Users\dbj\Downloads\clonezilla-util.v1.6.0.win-x64\ext\7-Zip\win-x64\7z.exe l -slt "Z:\589dca6f-a11d-4b9a-8525-e4f3eb362287 - Temp\9ce4dd06-8992-4760-99e7-81f9acd75f4a\8893d3bb-51db-4465-8943-0996ac208c9c"
Process encountered errors:
ERROR: Z:\589dca6f-a11d-4b9a-8525-e4f3eb362287 - Temp\9ce4dd06-8992-4760-99e7-81f9acd75f4a\8893d3bb-51db-4465-8943-0996ac208c9c : Z:\589dca6f-a11d-4b9a-8525-e4f3eb362287 - Temp\9ce4dd06-8992-4760-99e7-81f9acd75f4a\8893d3bb-51db-4465-8943-0996ac208c9c
Open ERROR: Cannot open the file as [Ext] archive


ERRORS:
Headers Error
Unexpected end of archive

   at libCommon.ProcessUtility.RunCommand(String cpath, String args, Boolean verbose, Boolean throwExceptionIfProcessHadErrors, Func`2 shouldStop)+MoveNext()
   at lib7Zip.SevenZipUtility.GetArchiveEntries(String archiveFilename, Boolean verbose, Boolean throwExceptionIfProcessHadErrors, Func`1 shouldStop)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 , Boolean& )
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.ImageFiles.RawImage.SetupFromStream(Stream rawImageStream, IEnumerable`1 archiveEntries, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.ImageFiles.CompressedImage..ctor(String filename, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, Folder tempFolder)
   at libClonezilla.PartitionContainers.ImageFiles.ImageFile..ctor(String filename, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.ExtractPartitionImage(ExtractPartitionImage extractPartitionImageOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)
```

**Comment by fiddyschmitt** [comment]
Thanks @DonBongJohn, I'll look into it.

Could you please post the contents of your `clonezilla-img` file?

**Comment by DonBongJohn** [comment]
Sorry what do you mean by that?

This was the folder clonezilla made.
![image](https://user-images.githubusercontent.com/20537257/184528055-79abc2a4-7cb3-40a0-9781-8f832cfb1f7f.png)


This is the file im actually trying to extract. Size compressed = ~50GB and uncompressed almost 100GB.
dbj/6450271C21B4E4F1/ocs_luks_Oeh.ext4-ptcl-img

**Comment by fiddyschmitt** [comment]
Thanks,

In that folder is a file called `clonezilla-img`. Could you please open it with a text editor and copy its contents into this thread? It helps me diagnose the partition in use.

In the meantime, the following command may work for you:
`clonezilla-util.exe mount --input "D:\2022-08-12-17-manjaro" -m L:\`

Could you please let me know if it works?

Thanks,
Fidel

**Comment by DonBongJohn** [comment]
`This image was saved by Clonezilla at 2022-08-12 17:31:17 UTC.
Saved by clonezilla-live-3.0.1-8-amd64.
The log during saving:
----------------------------------------------------------
Starting /usr/sbin/ocs-sr at 2022-08-12 17:13:40 UTC...
*****************************************************.
Clonezilla image dir: /home/partimag
Shutting down the Logical Volume Manager
Finished Shutting down the Logical Volume Manager
The selected devices: sdb1 sdb2 sdb5
PS. Beim nächsten Mal können Sie direkt den folgenden Befehl eingeben:
/usr/sbin/ocs-sr -luks yes -q2 -c -j2 -z1p -i 0 -sfsck -senc -p true saveparts 2022-08-12-17-manjaro sdb1 sdb2 sdb5
*****************************************************.
The selected devices: sdb1 sdb2 sdb5
Im nächsten Schritt wird die Festplatte oder die Partitionen auf diesem System als Image gesichert:
*****************************************************.
Machine: System Product Name
sdb1 (512M_ntfs(In_SanDisk_SDSSDH3_)_SanDisk_SDSSDH3_500G_193655800294)
sdb2 (100M_vfat(In_SanDisk_SDSSDH3_)_SanDisk_SDSSDH3_500G_193655800294)
sdb5 (108.7G_crypto_LUKS(In_SanDisk_SDSSDH3_)_SanDisk_SDSSDH3_500G_193655800294)
*****************************************************.
-> "/home/partimag/2022-08-12-17-manjaro".
Shutting down the Logical Volume Manager
Finished Shutting down the Logical Volume Manager
*****************************************************.
LUKS-Device jetzt geöffnet: /dev/sdb5
Running: cryptsetup open --type luks /dev/sdb5 ocs_luks_Oeh
Starting saving /dev/sdb1 as /home/partimag/2022-08-12-17-manjaro/sdb1.XXX...
/dev/sdb1 filesystem: ntfs.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.ntfs -z 10485760 -N -L /var/log/partclone.log -c -s /dev/sdb1 --output - | pigz -c --fast -b 1024 --rsyncable > /home/partimag/2022-08-12-17-manjaro/sdb1.ntfs-ptcl-img.gz 2> /tmp/img_out_err.NCghQN
Partclone v0.3.20 http://partclone.org
Starting to clone device (/dev/sdb1) to image (-)
Reading Super Block
memory needed: 20987908 bytes
bitmap 16384 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 
done!
File system:  NTFS
Device size:  536.9 MB = 131071 Blocks
Space in use:   8.8 MB = 2150 Blocks
Free Space:   528.1 MB = 128921 Blocks
Block size:   4096 Byte
Total block 131071
Syncing... OK!
Partclone successfully cloned the device (/dev/sdb1) to the image (-)
>>> Time elapsed: 7.11 secs (~ .118 mins)
*****************************************************.
Finished saving /dev/sdb1 as /home/partimag/2022-08-12-17-manjaro/sdb1.ntfs-ptcl-img.gz
*****************************************************.
Starting saving /dev/sdb2 as /home/partimag/2022-08-12-17-manjaro/sdb2.XXX...
/dev/sdb2 filesystem: vfat.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.vfat -z 10485760 -N -L /var/log/partclone.log -c -s /dev/sdb2 --output - | pigz -c --fast -b 1024 --rsyncable > /home/partimag/2022-08-12-17-manjaro/sdb2.vfat-ptcl-img.gz 2> /tmp/img_out_err.R7YklR
Partclone v0.3.20 http://partclone.org
Starting to clone device (/dev/sdb2) to image (-)
Reading Super Block
memory needed: 20997124 bytes
bitmap 25600 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 
done!
File system:  FAT32
Device size:  104.9 MB = 204800 Blocks
Space in use:  30.8 MB = 60222 Blocks
Free Space:    74.0 MB = 144578 Blocks
Block size:   512 Byte
Total block 204800
Syncing... OK!
Partclone successfully cloned the device (/dev/sdb2) to the image (-)
>>> Time elapsed: 7.14 secs (~ .119 mins)
*****************************************************.
Finished saving /dev/sdb2 as /home/partimag/2022-08-12-17-manjaro/sdb2.vfat-ptcl-img.gz
*****************************************************.
Starting saving /dev/mapper/ocs_luks_Oeh as /home/partimag/2022-08-12-17-manjaro/ocs_luks_Oeh.XXX...
/dev/mapper/ocs_luks_Oeh filesystem: ext4.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.ext4 -z 10485760 -N -L /var/log/partclone.log -c -s /dev/mapper/ocs_luks_Oeh --output - | pigz -c --fast -b 1024 --rsyncable > /home/partimag/2022-08-12-17-manjaro/ocs_luks_Oeh.ext4-ptcl-img.gz 2> /tmp/img_out_err.jmZwua
Partclone v0.3.20 http://partclone.org
Starting to clone device (/dev/mapper/ocs_luks_Oeh) to image (-)
Reading Super Block
memory needed: 24533413 bytes
bitmap 3561889 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 
done!
File system:  EXTFS
Device size:  116.7 GB = 28495105 Blocks
Space in use: 103.8 GB = 25348911 Blocks
Free Space:    12.9 GB = 3146194 Blocks
Block size:   4096 Byte
Total block 28495105
Syncing... OK!
Partclone successfully cloned the device (/dev/mapper/ocs_luks_Oeh) to the image (-)
>>> Time elapsed: 819.71 secs (~ 13.661 mins)
*****************************************************.
Finished saving /dev/mapper/ocs_luks_Oeh as /home/partimag/2022-08-12-17-manjaro/ocs_luks_Oeh.ext4-ptcl-img.gz
*****************************************************.
Dumping the device mapper table in /home/partimag/2022-08-12-17-manjaro/dmraid.table...
Saving block devices info in /home/partimag/2022-08-12-17-manjaro/blkdev.list...
Saving block devices attributes in /home/partimag/2022-08-12-17-manjaro/blkid.list...
Checking the integrity of partition table in the disk /dev/sdb... 
Reading the partition table for /dev/sdb...RETVAL=0
*****************************************************.
Saving the primary GPT of sdb as /home/partimag/2022-08-12-17-manjaro/sdb-gpt-1st by dd...
34+0 records in
34+0 records out
17408 bytes (17 kB, 17 KiB) copied, 0.00066851 s, 26.0 MB/s
*****************************************************.
Saving the secondary GPT of sdb as /home/partimag/2022-08-12-17-manjaro/sdb-gpt-2nd by dd...
32+0 records in
32+0 records out
16384 bytes (16 kB, 16 KiB) copied, 0.00111674 s, 14.7 MB/s
*****************************************************.
Saving the GPT of sdb as /home/partimag/2022-08-12-17-manjaro/sdb-gpt.gdisk by gdisk...
The operation has completed successfully.
*****************************************************.
Saving the MBR data for sdb...
1+0 Datensätze ein
1+0 Datensätze aus
512 Bytes kopiert, 0,00062242 s, 823 kB/s
End of saveparts job for image /home/partimag/2022-08-12-17-manjaro.
Checking if udevd rules have to be restored...
This program is not started by Clonezilla server, so skip notifying it the job is done.
This program is not started by Clonezilla server, so skip notifying it the job is done.
Finished!
Finished!
### End of log ###
### Image created time: 2022-0812-1731
`
The recommended command from you didn't work.

`PS C:\Users\dbj\Downloads\clonezilla-util.v1.6.0.win-x64> .\clonezilla-util.exe mount --input "D:\2022-08-12-17-manjaro" -m L:\
[16:21:55 INF] clonezilla-util v1.6.0
[16:21:55 INF] [2022-08-12-17-manjaro] [sdb1] Finding optimal decompressor (seekable/sequential)
[16:21:55 INF] [2022-08-12-17-manjaro] [sdb1] Loading partition information
[16:21:55 INF] [2022-08-12-17-manjaro] [sdb2] Finding optimal decompressor (seekable/sequential)
[16:21:55 INF] [2022-08-12-17-manjaro] [sdb2] Loading partition information
Unhandled exception. System.Exception: Could not determine compression used by partition sdb5 in: D:\2022-08-12-17-manjaro
   at libClonezilla.PartitionContainers.ClonezillaImage.GetCompressionInUse(String clonezillaArchiveFolder, String partitionName)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__2(String partitionName)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable )+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 )
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.ClonezillaImage..ctor(String clonezillaArchiveFolder, IClonezillaCacheManager cacheManager, List`1 partitionsToLoad, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.MountAsFiles(MountAsFiles mountAsFilesOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)`

**Comment by fiddyschmitt** [comment]
Thanks,

It looks like the source drive was encrypted with luks. I've never tried that, so I'll have to look into it.

Cheers,
Fidel

**Comment by fiddyschmitt** [comment]
Hi Don,

It doesn't look like there's an easy way for me to implement LUKS support in Windows.

Tomorrow I'll type up a comprehensive guide of how to extract files from `ocs_luks_Oeh.ext4-ptcl-img.gz`, using Linux. Specifically using Clonezilla in a Virtual Machine.

Cheers,
Fidel

**Comment by DonBongJohn** [comment]
Hey Fidel,

thank you very much for your efforts. You won't believe me how hard I was struggling with this image and ended up writing you this issue to get with someone in touch that knows stuff about clonezilla. It took me a whole weekend looking up stuff and in the end I even gave up on this image. At least I have saved all my data on an unencrypted drive before that hassle.

Do you have any recommendations for an easy backup solutions for home users by any chance? Preferably with an GUI. 
I'm too scared to use clonezilla again. As of now I'm using Timeshift in Manjaro since it has no issues with an LUKS encrypted drive and veeam agent on Windows.

**Comment by fiddyschmitt** [comment]
Hi Don,

It turns out the contents are not encrypted, so there are less steps to extract files.

- Install VirtualBox
- Create a VM with:
	- A virtual DVD drive with the Clonezilla iso
	- Shared Folder
		- Folder Path: D:\
		- Folder Name: D_DRIVE
- Start the VM
- Choose:
	- Clonezilla live (To RAM)
	- Pick a language
	- Keyboard layout: Keep
	- Select 'Enter Shell'
	
`sudo su -`

- mount your shared folder:
	`mkdir /media/d`
	`mount -t vboxsf D_DRIVE /media/d`
	
- confirm you can see files in your shared folder:
	`cd /media/d`
	`ls -lah`
	
- if your file is compressed with gz, use this:
	`gunzip "ocs_luks_OLi.ext4-ptcl-img.gz" | partclone.restore --restore_raw_file -C -s - -o extracted.img`
	
- if your file is compressed with Zstandard, use this:
	`zstdcat "ocs_luks_OLi.ext4-ptcl-img.zst" | partclone.restore --restore_raw_file -C -s - -o extracted.img`
	
- if your file is already decompressed, use this:
	`cat "ocs_luks_OLi.ext4-ptcl-img" | partclone.restore --restore_raw_file -C -s - -o extracted.img`
	
You can then open `extracted.img` using 7-Zip, and extract whatever you need.

**Comment by fiddyschmitt** [comment]
Hi Don,

I've just released [v1.7.0](https://github.com/fiddyschmitt/clonezilla-util/releases/tag/v1.7.0).

You can now use your original command:
`clonezilla-util.exe extract-partition-image --input "D:\2022-08-12-17-manjaro\ocs_luks_Oeh.ext4-ptcl-img.gz" --output D:\IMG`

And if you wanted to mount rather than extract, use:
`clonezilla-util.exe mount --input "D:\2022-08-12-17-manjaro\ocs_luks_Oeh.ext4-ptcl-img.gz" -m L:\`

**Comment by DonBongJohn** [comment]
Thank you very much Fidel for your effort!
I came a bit further with the new version however I'm still not able to get the files decrypted.

With the original command I can't open the extracted IMG with 7zip.
I get an error saying that the archive is corrupted.

When I want to mount the IMG I get an error saying that the virtual drive cannot be accessed.
Same goes for the second command you send me.
Might this be an issue with the dokan driver?

Regards

**Comment by fiddyschmitt** [comment]
Thanks Don, no worries! :)

Could you please delete the `cache` folder (where clonezilla-util.exe is) and try the above two commands again?

**Comment by DonBongJohn** [comment]
Hey Fidel, that's the last output from the powershell.

[03:52:25 INF] Extracted 108,7 GB / 108,7 GB    (100% through source file)

Opening the file results in a popup saying that the image is corrupted.
I then tried to mount the IMG. 
`.\clonezilla-util.exe mount --input "D:\IMG\ocs_luks_Oeh.ext4-ptcl-img.img" --mount Y:\`

https://pastebin.com/CjKTcXSW

I am now trying to mount the ocs_luks_Oeh.ext4-ptcl-img from the backup folder with the other command.

**Comment by fiddyschmitt** [comment]
Thanks Don!

When I captured a LUKS partition using Clonezilla, it prompted me for the password. I think Clonezilla has two modes:

- Provide password (which results in a small, unencrypted backup)
- Don't provide password (which results in a large, encrypted backup)

Do you recall if you provided your password to Clonezilla when you made the backup?

**Comment by DonBongJohn** [comment]
Sorry I would only know the password but not if I got prompted to type it in.
